defaults:
  - name: auth-service
    namespace: kube-public
    local_port: 50013
    remote_port: 80
  - name: user-service
    namespace: kube-public
    local_port: 50014
    remote_port: 80

groups:
  - name: backend
    services:
      - name: auth-service
        namespace: kube-public
        remote_port: 80
        local_port: 50013
      - name: user-service-2
        namespace: kube-public
        remote_port: 80
        local_port: 50010
